### ISSUE TITLE
Can not find any timezone configuration

### ISSUE THREAD

**Issue by RayBB** [pyro2927/SouthwestCheckin#36]
I cloned the repo than run the `sudo docker run -it pyro2927/southwestcheckin:latest CONFIRMATION_NUMBER FIRST_NAME LAST_NAME` command but I'm getting the following error.

```
Unable to find image 'pyro2927/southwestcheckin:latest' locally
latest: Pulling from pyro2927/southwestcheckin
8e402f1a9c57: Pull complete 
cda9ba2397ef: Pull complete 
d7153c29df0e: Pull complete 
cbbf0d0a5ee3: Pull complete 
c142a4eca653: Pull complete 
e329b51c01e5: Pull complete 
b43049af01c5: Pull complete 
b65c5ad0a9ae: Pull complete 
1c813d1d44c4: Pull complete 
Digest: sha256:f79e3db08e9993bbe95963e6314a8a49c50ae9512b2fe0a944afc21380e24020
Status: Downloaded newer image for pyro2927/southwestcheckin:latest
Traceback (most recent call last):
  File "./checkin.py", line 104, in <module>
    auto_checkin(reservation_number, first_name, last_name, notifications)
  File "./checkin.py", line 55, in auto_checkin
    now = datetime.now(utc).astimezone(get_localzone())
  File "/usr/local/lib/python3.7/site-packages/tzlocal/unix.py", line 131, in get_localzone
    _cache_tz = _get_localzone()
  File "/usr/local/lib/python3.7/site-packages/tzlocal/unix.py", line 125, in _get_localzone
    raise pytz.UnknownTimeZoneError('Can not find any timezone configuration')
pytz.exceptions.UnknownTimeZoneError: 'Can not find any timezone configuration'
```

**Comment by marshall007** [comment]
This solution worked for me: https://unix.stackexchange.com/a/110529

```
$ docker run -it pyro2927/southwestcheckin:latest "/bin/sh"

/usr/src/app # ln -s /usr/share/zoneinfo/Etc/GMT+6 /etc/localtime
/usr/src/app # ./entrypoint.sh CONFIRMATION_NUMBER FIRST_NAME LAST_NAME
```

**Comment by MikeFielden** [comment]
@marshall007 this corrects the issue for me thank you

**Comment by Drewster727** [comment]
Also, you could pass in the TZ environment variable:
`sudo docker run -it -e TZ=America/Chicago pyro2927/southwestcheckin:latest CONFIRMATION_NUMBER FIRST_NAME LAST_NAME`

**Comment by pyro2927** [comment]
Closing for now, as the code has been refactored to not need local timezones.
