### ISSUE TITLE
TypeError: request() got an unexpected keyword argument 'json'

### ISSUE THREAD

**Issue by stgreenb** [pyro2927/SouthwestCheckin#51]
Run from python 2.7 (not docker, which failed see other ticket) on amazon ec2 errors on recent trip. 

```
Attempting check-in...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 804, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 757, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./checkin.py", line 43, in schedule_checkin
    data = reservation.checkin()
  File "/home/ec2-user/swc/SouthwestCheckin/southwest/southwest.py", line 81, in checkin
    confirmation = self.load_json_page(url, info_needed['body'])
  File "/home/ec2-user/swc/SouthwestCheckin/southwest/southwest.py", line 59, in load_json_page
    data = self.safe_request(url, body)
  File "/home/ec2-user/swc/SouthwestCheckin/southwest/southwest.py", line 42, in safe_request
    r = requests.post(url, headers=headers, json=body)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 88, in post
    return request('post', url, data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
TypeError: request() got an unexpected keyword argument 'json'
```

**Comment by pandabear41** [comment]
Did you set a notification? I had the same problem when I added a SMS notification.

**Comment by scho7623** [comment]
I'm still seeing this error message. Was this resolved? Any workarounds? cc: @stgreenb @pandabear41

**Comment by pandabear41** [comment]
@scho7623 
The error with notification fixed a while ago then shortly after that feature was removed. 
Otherwise you are running a super old version of requests. Can you find what version of requests you are running?
python -c "import requests; print(requests.__version__)"

You can try upgrading requests.

**Comment by scho7623** [comment]
Thanks @pandabear41 , it was indeed super old `2.2.1`. I upgraded to `2.22.0` and it works fine now. Thanks.

**Comment by urllib** [comment]
Is there a change in the anti-climbing strategy？Can you explain that?
